title: luiza marinho
description: .net developer and ai enthusiast
theme: just-the-docs
nav_enabled: true
layout: minimal

url: https://luiza.dev

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
