baseURL = "https://www.luiza.dev/"
title = "hello, i'm luiza"
author = "Luiza Marinho"
defaultContentLanguage = "pt-br"
defaultContentLanguageInSubdir = false
enableInlineShortcodes = true
ignoreFiles = ["(projects/(test3|test4)|write/(test|test2))\\.md$"]

[languages]
  [languages.pt-br]
    languageCode = "pt-BR"
    languageName = "Português (Brasil)"
    weight = 1

    [[languages.pt-br.menus.main]]
    identifier = "home"
    name = "início"
    pageRef = "/"
    weight = 1

    [[languages.pt-br.menus.main]]
    identifier = "projects"
    name = "projetos"
    pageRef = "/projects"
    weight = 2

    [[languages.pt-br.menus.main]]
    identifier = "resume"
    name = "currículo"
    pageRef = "/resume"
    weight = 3

    [[languages.pt-br.menus.main]]
    identifier = "about"
    name = "sobre mim"
    pageRef = "/about"
    weight = 4

  [languages.en]
    languageCode = "en-US"
    languageName = "English"
    weight = 2

    [[languages.en.menus.main]]
    identifier = "home"
    name = "home"
    pageRef = "/"
    weight = 1

    [[languages.en.menus.main]]
    identifier = "projects"
    name = "projects"
    pageRef = "/projects"
    weight = 2

    [[languages.en.menus.main]]
    identifier = "resume"
    name = "resume"
    pageRef = "/resume"
    weight = 3

    [[languages.en.menus.main]]
    identifier = "about"
    name = "about me"
    pageRef = "/about"
    weight = 4

[markup.goldmark.renderer]
  unsafe = true
